/* A recursive-descent parser generated by peg 0.1.2 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <ctype.h>
#define YYRULECOUNT 40

# include "tree.h"
# include "version.h"

# include <stdio.h>
# include <stdlib.h>
# include <unistd.h>
# include <string.h>
# include <libgen.h>
# include <assert.h>

  typedef struct Header Header;

  struct Header {
    char   *text;
    Header *next;
  };

  FILE *input= 0;

  int   verboseFlag= 0;

  static int	 lineNumber= 0;
  static char	*fileName= 0;
  static char	*trailer= 0;
  static Header	*headers= 0;

  void makeHeader(char *text);
  void makeTrailer(char *text);

  void yyerror(char *message);

# define YY_INPUT(buf, result, max)		\
  {						\
    int c= getc(input);				\
    if ('\n' == c || '\r' == c) ++lineNumber;	\
    result= (EOF == c) ? 0 : (*(buf)= c, 1);	\
  }

# define YY_LOCAL(T)	static T
# define YY_RULE(T)	static T

#ifndef YY_VARIABLE
#define YY_VARIABLE(T)	static T
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( mybegin= yybegin= yypos, 1)
#endif
#ifndef YY_END
#define YY_END		( myend= yyend= yypos, 1)
#endif
#ifndef YY_MYBEGIN
#define YY_MYBEGIN	( mybegin= yybegin= yypos, 1)
#endif
#ifndef YY_MYEND
#define YY_MYEND	( myend= yyend= yypos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YY_DIE
# define YY_DIE(args)	fprintf(stderr, args); exit(-1);
#endif
#ifndef YY_OUTPUT
# define YY_OUTPUT(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef mytext
#define mytext myText(yythisthunk->mybegin, yythisthunk->myend)
#endif

#ifndef YY_PART

typedef void (*yyaction)(char *yytext, int yyleng);
typedef struct _yythunk { int begin, end, mybegin, myend;  yyaction  action;  struct _yythunk *next; } yythunk;

YY_VARIABLE(char *   ) yybuf= 0;
YY_VARIABLE(int	     ) yybuflen= 0;
YY_VARIABLE(int	     ) yypos= 0;
YY_VARIABLE(int	     ) yylimit= 0;
YY_VARIABLE(char *   ) yytext= 0;
YY_VARIABLE(int	     ) yytextlen= 0;
YY_VARIABLE(int	     ) yybegin= 0;
YY_VARIABLE(int	     ) yyend= 0;
YY_VARIABLE(int	     ) yytextmax= 0;
YY_VARIABLE(yythunk *) yythunks= 0;
YY_VARIABLE(int	     ) yythunkslen= 0;
YY_VARIABLE(int      ) yythunkpos= 0;
YY_VARIABLE(yythunk *) yythisthunk= 0;
YY_VARIABLE(char *   ) yythisrule= 0;
YY_VARIABLE(YYSTYPE  ) yy;
YY_VARIABLE(YYSTYPE *) yyval= 0;
YY_VARIABLE(YYSTYPE *) yyvals= 0;
YY_VARIABLE(int      ) yyvalslen= 0;
YY_VARIABLE(long long int) yyaccepted= 0;

YY_LOCAL(int) yyrefill(void)
{
  int yyn;
  while (yybuflen - yypos < 512)
    {
      if (yybuflen > 10000000) {
        YY_DIE("look ahead exceeds 10MB, giving up.\n");
      }
      yybuflen *= 2;
      yybuf= realloc(yybuf, yybuflen);
    }
  YY_INPUT((yybuf + yypos), yyn, (yybuflen - yypos));
  if (!yyn) return 0;
  yylimit += yyn;
  return 1;
}

static char* yyunmatched(void) {
	static char copy[45];
	int pos = 0;
	while (pos < 40) {
		if (yypos+pos >= yylimit) break;
		char ch = yybuf[yypos+pos];
		if (ch == '\n') {
			copy[pos++] = '\\';
			copy[pos++] = 'n';
			break;
		}
		copy[pos++] = ch;
	}
	if (yypos+pos < yylimit) {
		copy[pos++]='.';
		copy[pos++]='.';
		copy[pos++]='.';
	}
	copy[pos] = '\0';
	return copy;
}

YY_LOCAL(int) yymatchDot(void)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  ++yypos;
  return 1;
}

YY_LOCAL(int) yymatchChar(int c)
{
  if (yypos >= yylimit && !yyrefill()) return 0;
  if (yybuf[yypos] == c)
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, yyunmatched()));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, yyunmatched()));
  return 0;
}

YY_LOCAL(int) yymatchString(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (yybuf[yypos] != *s)
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchStringCaseInsensitive(char *s)
{
  int yysav= yypos;
  while (*s)
    {
      if (yypos >= yylimit && !yyrefill()) return 0;
      if (tolower(yybuf[yypos]) != tolower(*s))
        {
          yypos= yysav;
          return 0;
        }
      ++s;
      ++yypos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(unsigned char *bits)
{
  int c;
  if (yypos >= yylimit && !yyrefill()) return 0;
  c= yybuf[yypos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yypos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yyunmatched()));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yyunmatched()));
  return 0;
}

YY_LOCAL(void) yyDo(yyaction action, int begin, int end, int mybegin, int myend)
{
  while (yythunkpos >= yythunkslen)
    {
      if (yythunkslen > 2000000) {
        YY_DIE("thunk storage exceeds 2MB, giving up.\n");
      }
      yythunkslen *= 2;
      yythunks= realloc(yythunks, sizeof(yythunk) * yythunkslen);
    }
  yythunks[yythunkpos].begin=  begin;
  yythunks[yythunkpos].end=    end;
  yythunks[yythunkpos].mybegin=  mybegin;
  yythunks[yythunkpos].myend=    myend;
  yythunks[yythunkpos].action= action;
  ++yythunkpos;
}

YY_LOCAL(int) yyText(int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yytextlen < (yyleng - 1))
      {
        if (yytextlen > 2000000) {
          YY_DIE("yytext exceeds 2MB, giving up.\n");
        }
        yytextlen *= 2;
        yytext= realloc(yytext, yytextlen);
      }
      memcpy(yytext, yybuf + begin, yyleng);
    }
  yytext[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(char *) myText(int begin, int end)
{
  yyText(begin, end);
  return yytext;
}

YY_LOCAL(void) yyDone(void)
{
  int pos;
  for (pos= 0;  pos < yythunkpos;  ++pos)
    {
      yythunk *thunk= &yythunks[pos];
      yythisthunk = thunk;
      int yyleng= thunk->end ? yyText(thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yytext));
      thunk->action(yytext, yyleng);
    }
  yythunkpos= 0;
}

YY_LOCAL(void) yyCommit()
{
  YY_OUTPUT((yybuf, yypos));
  if ((yylimit -= yypos))
    {
      memmove(yybuf, yybuf + yypos, yylimit);
    }
  yybegin -= yypos;
  yyend -= yypos;
  yyaccepted += yypos;
  yypos= yythunkpos= 0;
}

YY_LOCAL(int) yyAccept(int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone();
      yyCommit();
    }
  return 1;
}

YY_LOCAL(void) yyPush(char *text, int count)	{ yyval += count; }
YY_LOCAL(void) yyPop(char *text, int count)	{ yyval -= count; }
YY_LOCAL(void) yySet(char *text, int count)	{ yyval[count]= yy; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yythunkpos0)

YY_RULE(int) yy_end_of_line(); /* 40 */
YY_RULE(int) yy_comment(); /* 39 */
YY_RULE(int) yy_space(); /* 38 */
YY_RULE(int) yy_braces(); /* 37 */
YY_RULE(int) yy_range(); /* 36 */
YY_RULE(int) yy_char(); /* 35 */
YY_RULE(int) yy_END(); /* 34 */
YY_RULE(int) yy_BEGIN(); /* 33 */
YY_RULE(int) yy_MYEND(); /* 32 */
YY_RULE(int) yy_MYEEND(); /* 31 */
YY_RULE(int) yy_MYBEGIN(); /* 30 */
YY_RULE(int) yy_MYBEEGIN(); /* 29 */
YY_RULE(int) yy_DOT(); /* 28 */
YY_RULE(int) yy_class(); /* 27 */
YY_RULE(int) yy_literal(); /* 26 */
YY_RULE(int) yy_CLOSE(); /* 25 */
YY_RULE(int) yy_OPEN(); /* 24 */
YY_RULE(int) yy_COLON(); /* 23 */
YY_RULE(int) yy_PLUS(); /* 22 */
YY_RULE(int) yy_STAR(); /* 21 */
YY_RULE(int) yy_QUESTION(); /* 20 */
YY_RULE(int) yy_primary(); /* 19 */
YY_RULE(int) yy_NOT(); /* 18 */
YY_RULE(int) yy_suffix(); /* 17 */
YY_RULE(int) yy_action(); /* 16 */
YY_RULE(int) yy_AND(); /* 15 */
YY_RULE(int) yy_prefix(); /* 14 */
YY_RULE(int) yy_BAR(); /* 13 */
YY_RULE(int) yy_sequence(); /* 12 */
YY_RULE(int) yy_SEMICOLON(); /* 11 */
YY_RULE(int) yy_expression(); /* 10 */
YY_RULE(int) yy_EQUAL(); /* 9 */
YY_RULE(int) yy_identifier(); /* 8 */
YY_RULE(int) yy_RPERCENT(); /* 7 */
YY_RULE(int) yy_end_of_file(); /* 6 */
YY_RULE(int) yy_trailer(); /* 5 */
YY_RULE(int) yy_definition(); /* 4 */
YY_RULE(int) yy_declaration(); /* 3 */
YY_RULE(int) yy__(); /* 2 */
YY_RULE(int) yy_grammar(); /* 1 */

YY_ACTION(void) yy_14_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_14_primary\n"));
   push(makePredicate("YY_END")); ;
}
YY_ACTION(void) yy_13_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_13_primary\n"));
   push(makePredicate("YY_BEGIN")); ;
}
YY_ACTION(void) yy_12_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_12_primary\n"));
   push(Sequence_append(makePredicate("YY_MYEND"),makeAction("YY_DOUBLE_END(yythisrule,mytext)"))); ;
}
YY_ACTION(void) yy_11_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_11_primary\n"));
   push(Sequence_append(makePredicate("YY_MYEND"),makeAction("YY_TRIPLE_END(yythisrule,mytext)"))); ;
}
YY_ACTION(void) yy_10_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_10_primary\n"));
   push(Sequence_append(makePredicate("YY_MYBEGIN"),makeAction("YY_DOUBLE_BEGIN(yythisrule)"))); ;
}
YY_ACTION(void) yy_9_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_9_primary\n"));
   push(Sequence_append(makePredicate("YY_MYBEGIN"),makeAction("YY_TRIPLE_BEGIN(yythisrule)"))); ;
}
YY_ACTION(void) yy_8_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_8_primary\n"));
   push(makeAction(yytext)); ;
}
YY_ACTION(void) yy_7_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_7_primary\n"));
   push(makeDot()); ;
}
YY_ACTION(void) yy_6_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_6_primary\n"));
   push(makeClass(yytext)); ;
}
YY_ACTION(void) yy_5_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_5_primary\n"));
   push(makeString(yytext)); ;
}
YY_ACTION(void) yy_4_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_4_primary\n"));
   push(makeStringCaseInsensitive(yytext)); ;
}
YY_ACTION(void) yy_3_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_3_primary\n"));
   push(makeName(findRule(yytext))); ;
}
YY_ACTION(void) yy_2_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_2_primary\n"));
   Node *name= makeName(findRule(yytext));  name->name.variable= pop();  push(name); ;
}
YY_ACTION(void) yy_1_primary(char *yytext, int yyleng)
{
  yythisrule = "primary";
  yyprintf((stderr, "do yy_1_primary\n"));
   push(makeVariable(yytext)); ;
}
YY_ACTION(void) yy_3_suffix(char *yytext, int yyleng)
{
  yythisrule = "suffix";
  yyprintf((stderr, "do yy_3_suffix\n"));
   push(makePlus (pop())); ;
}
YY_ACTION(void) yy_2_suffix(char *yytext, int yyleng)
{
  yythisrule = "suffix";
  yyprintf((stderr, "do yy_2_suffix\n"));
   push(makeStar (pop())); ;
}
YY_ACTION(void) yy_1_suffix(char *yytext, int yyleng)
{
  yythisrule = "suffix";
  yyprintf((stderr, "do yy_1_suffix\n"));
   push(makeQuery(pop())); ;
}
YY_ACTION(void) yy_3_prefix(char *yytext, int yyleng)
{
  yythisrule = "prefix";
  yyprintf((stderr, "do yy_3_prefix\n"));
   push(makePeekNot(pop())); ;
}
YY_ACTION(void) yy_2_prefix(char *yytext, int yyleng)
{
  yythisrule = "prefix";
  yyprintf((stderr, "do yy_2_prefix\n"));
   push(makePeekFor(pop())); ;
}
YY_ACTION(void) yy_1_prefix(char *yytext, int yyleng)
{
  yythisrule = "prefix";
  yyprintf((stderr, "do yy_1_prefix\n"));
   push(makePredicate(yytext)); ;
}
YY_ACTION(void) yy_1_sequence(char *yytext, int yyleng)
{
  yythisrule = "sequence";
  yyprintf((stderr, "do yy_1_sequence\n"));
   Node *f= pop();  push(Sequence_append(pop(), f)); ;
}
YY_ACTION(void) yy_1_expression(char *yytext, int yyleng)
{
  yythisrule = "expression";
  yyprintf((stderr, "do yy_1_expression\n"));
   Node *f= pop();  push(Alternate_append(pop(), f)); ;
}
YY_ACTION(void) yy_2_definition(char *yytext, int yyleng)
{
  yythisrule = "definition";
  yyprintf((stderr, "do yy_2_definition\n"));
   Node *e= pop();  Rule_setExpression(pop(), e); ;
}
YY_ACTION(void) yy_1_definition(char *yytext, int yyleng)
{
  yythisrule = "definition";
  yyprintf((stderr, "do yy_1_definition\n"));
   if (push(beginRule(findRule(yytext)))->rule.expression)
							    fprintf(stderr, "rule '%s' redefined\n", yytext); ;
}
YY_ACTION(void) yy_1_trailer(char *yytext, int yyleng)
{
  yythisrule = "trailer";
  yyprintf((stderr, "do yy_1_trailer\n"));
   makeTrailer(yytext); ;
}
YY_ACTION(void) yy_1_declaration(char *yytext, int yyleng)
{
  yythisrule = "declaration";
  yyprintf((stderr, "do yy_1_declaration\n"));
   makeHeader(yytext); ;
}

YY_RULE(int) yy_end_of_line()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "end_of_line"));
  {  int yypos2= yypos, yythunkpos2= yythunkpos;  if (!yymatchString("\r\n")) goto l3;  goto l2;
  l3:;	  yypos= yypos2; yythunkpos= yythunkpos2;  if (!yymatchChar('\n')) goto l4;  goto l2;
  l4:;	  yypos= yypos2; yythunkpos= yythunkpos2;  if (!yymatchChar('\r')) goto l1;
  }
  l2:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "end_of_line", yyunmatched()));
  return 1;
  l1:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "end_of_line", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_comment()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "comment"));  if (!yymatchChar('#')) goto l5;
  l6:;	
  {  int yypos7= yypos, yythunkpos7= yythunkpos;
  {  int yypos8= yypos, yythunkpos8= yythunkpos;  if (!yy_end_of_line()) goto l8;  goto l7;
  l8:;	  yypos= yypos8; yythunkpos= yythunkpos8;
  }  if (!yymatchDot()) goto l7;  goto l6;
  l7:;	  yypos= yypos7; yythunkpos= yythunkpos7;
  }  if (!yy_end_of_line()) goto l5;
  yyprintf((stderr, "  ok   %s @ %s\n", "comment", yyunmatched()));
  return 1;
  l5:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "comment", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_space()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "space"));
  {  int yypos10= yypos, yythunkpos10= yythunkpos;  if (!yymatchChar(' ')) goto l11;  goto l10;
  l11:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yymatchChar('\t')) goto l12;  goto l10;
  l12:;	  yypos= yypos10; yythunkpos= yythunkpos10;  if (!yy_end_of_line()) goto l9;
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "space", yyunmatched()));
  return 1;
  l9:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "space", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_braces()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "braces"));
  {  int yypos14= yypos, yythunkpos14= yythunkpos;  if (!yymatchChar('{')) goto l15;
  l16:;	
  {  int yypos17= yypos, yythunkpos17= yythunkpos;
  {  int yypos18= yypos, yythunkpos18= yythunkpos;  if (!yymatchChar('}')) goto l18;  goto l17;
  l18:;	  yypos= yypos18; yythunkpos= yythunkpos18;
  }  if (!yymatchDot()) goto l17;  goto l16;
  l17:;	  yypos= yypos17; yythunkpos= yythunkpos17;
  }  if (!yymatchChar('}')) goto l15;  goto l14;
  l15:;	  yypos= yypos14; yythunkpos= yythunkpos14;
  {  int yypos19= yypos, yythunkpos19= yythunkpos;  if (!yymatchChar('}')) goto l19;  goto l13;
  l19:;	  yypos= yypos19; yythunkpos= yythunkpos19;
  }  if (!yymatchDot()) goto l13;
  }
  l14:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "braces", yyunmatched()));
  return 1;
  l13:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "braces", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_range()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "range"));
  {  int yypos21= yypos, yythunkpos21= yythunkpos;  if (!yy_char()) goto l22;  if (!yymatchChar('-')) goto l22;  if (!yy_char()) goto l22;  goto l21;
  l22:;	  yypos= yypos21; yythunkpos= yythunkpos21;  if (!yy_char()) goto l20;
  }
  l21:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "range", yyunmatched()));
  return 1;
  l20:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "range", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_char()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "char"));
  {  int yypos24= yypos, yythunkpos24= yythunkpos;  if (!yymatchChar('\\')) goto l25;  if (!yymatchClass((unsigned char *)"\000\000\000\000\204\000\000\000\000\000\000\070\146\100\124\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l25;  goto l24;
  l25:;	  yypos= yypos24; yythunkpos= yythunkpos24;  if (!yymatchChar('\\')) goto l26;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\017\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;  goto l24;
  l26:;	  yypos= yypos24; yythunkpos= yythunkpos24;  if (!yymatchChar('\\')) goto l27;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l27;
  {  int yypos28= yypos, yythunkpos28= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\000\377\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l28;  goto l29;
  l28:;	  yypos= yypos28; yythunkpos= yythunkpos28;
  }
  l29:;	  goto l24;
  l27:;	  yypos= yypos24; yythunkpos= yythunkpos24;
  {  int yypos30= yypos, yythunkpos30= yythunkpos;  if (!yymatchChar('\\')) goto l30;  goto l23;
  l30:;	  yypos= yypos30; yythunkpos= yythunkpos30;
  }  if (!yymatchDot()) goto l23;
  }
  l24:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "char", yyunmatched()));
  return 1;
  l23:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "char", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_END()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "END"));  if (!yymatchChar('>')) goto l31;  if (!yy__()) goto l31;
  yyprintf((stderr, "  ok   %s @ %s\n", "END", yyunmatched()));
  return 1;
  l31:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "END", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_BEGIN()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "BEGIN"));  if (!yymatchChar('<')) goto l32;  if (!yy__()) goto l32;
  yyprintf((stderr, "  ok   %s @ %s\n", "BEGIN", yyunmatched()));
  return 1;
  l32:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BEGIN", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_MYEND()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MYEND"));  if (!yymatchString(">>")) goto l33;  if (!yy__()) goto l33;
  yyprintf((stderr, "  ok   %s @ %s\n", "MYEND", yyunmatched()));
  return 1;
  l33:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MYEND", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_MYEEND()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MYEEND"));  if (!yymatchString(">>>")) goto l34;  if (!yy__()) goto l34;
  yyprintf((stderr, "  ok   %s @ %s\n", "MYEEND", yyunmatched()));
  return 1;
  l34:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MYEEND", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_MYBEGIN()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MYBEGIN"));  if (!yymatchString("<<")) goto l35;  if (!yy__()) goto l35;
  yyprintf((stderr, "  ok   %s @ %s\n", "MYBEGIN", yyunmatched()));
  return 1;
  l35:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MYBEGIN", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_MYBEEGIN()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "MYBEEGIN"));  if (!yymatchString("<<<")) goto l36;  if (!yy__()) goto l36;
  yyprintf((stderr, "  ok   %s @ %s\n", "MYBEEGIN", yyunmatched()));
  return 1;
  l36:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MYBEEGIN", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_DOT()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "DOT"));  if (!yymatchChar('.')) goto l37;  if (!yy__()) goto l37;
  yyprintf((stderr, "  ok   %s @ %s\n", "DOT", yyunmatched()));
  return 1;
  l37:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DOT", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_class()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "class"));  if (!yymatchChar('[')) goto l38;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l38;
  l39:;	
  {  int yypos40= yypos, yythunkpos40= yythunkpos;
  {  int yypos41= yypos, yythunkpos41= yythunkpos;  if (!yymatchChar(']')) goto l41;  goto l40;
  l41:;	  yypos= yypos41; yythunkpos= yythunkpos41;
  }  if (!yy_range()) goto l40;  goto l39;
  l40:;	  yypos= yypos40; yythunkpos= yythunkpos40;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l38;  if (!yymatchChar(']')) goto l38;  if (!yy__()) goto l38;
  yyprintf((stderr, "  ok   %s @ %s\n", "class", yyunmatched()));
  return 1;
  l38:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "class", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_literal()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "literal"));
  {  int yypos43= yypos, yythunkpos43= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l44;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l44;
  l45:;	
  {  int yypos46= yypos, yythunkpos46= yythunkpos;
  {  int yypos47= yypos, yythunkpos47= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l47;  goto l46;
  l47:;	  yypos= yypos47; yythunkpos= yythunkpos47;
  }  if (!yy_char()) goto l46;  goto l45;
  l46:;	  yypos= yypos46; yythunkpos= yythunkpos46;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l44;  if (!yymatchClass((unsigned char *)"\000\000\000\000\200\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l44;  if (!yy__()) goto l44;  goto l43;
  l44:;	  yypos= yypos43; yythunkpos= yythunkpos43;  if (!yymatchClass((unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l42;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l42;
  l48:;	
  {  int yypos49= yypos, yythunkpos49= yythunkpos;
  {  int yypos50= yypos, yythunkpos50= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l50;  goto l49;
  l50:;	  yypos= yypos50; yythunkpos= yythunkpos50;
  }  if (!yy_char()) goto l49;  goto l48;
  l49:;	  yypos= yypos49; yythunkpos= yythunkpos49;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l42;  if (!yymatchClass((unsigned char *)"\000\000\000\000\004\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l42;  if (!yy__()) goto l42;
  }
  l43:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "literal", yyunmatched()));
  return 1;
  l42:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "literal", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_CLOSE()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "CLOSE"));  if (!yymatchChar(')')) goto l51;  if (!yy__()) goto l51;
  yyprintf((stderr, "  ok   %s @ %s\n", "CLOSE", yyunmatched()));
  return 1;
  l51:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CLOSE", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_OPEN()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "OPEN"));  if (!yymatchChar('(')) goto l52;  if (!yy__()) goto l52;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPEN", yyunmatched()));
  return 1;
  l52:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPEN", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_COLON()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "COLON"));  if (!yymatchChar(':')) goto l53;  if (!yy__()) goto l53;
  yyprintf((stderr, "  ok   %s @ %s\n", "COLON", yyunmatched()));
  return 1;
  l53:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COLON", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_PLUS()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "PLUS"));  if (!yymatchChar('+')) goto l54;  if (!yy__()) goto l54;
  yyprintf((stderr, "  ok   %s @ %s\n", "PLUS", yyunmatched()));
  return 1;
  l54:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLUS", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_STAR()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "STAR"));  if (!yymatchChar('*')) goto l55;  if (!yy__()) goto l55;
  yyprintf((stderr, "  ok   %s @ %s\n", "STAR", yyunmatched()));
  return 1;
  l55:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STAR", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_QUESTION()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "QUESTION"));  if (!yymatchChar('?')) goto l56;  if (!yy__()) goto l56;
  yyprintf((stderr, "  ok   %s @ %s\n", "QUESTION", yyunmatched()));
  return 1;
  l56:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QUESTION", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_primary()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "primary"));
  {  int yypos58= yypos, yythunkpos58= yythunkpos;  if (!yy_identifier()) goto l59;  yyDo(yy_1_primary, yybegin, yyend, mybegin, myend);  if (!yy_COLON()) goto l59;  if (!yy_identifier()) goto l59;
  {  int yypos60= yypos, yythunkpos60= yythunkpos;  if (!yy_EQUAL()) goto l60;  goto l59;
  l60:;	  yypos= yypos60; yythunkpos= yythunkpos60;
  }  yyDo(yy_2_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l59:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_identifier()) goto l61;
  {  int yypos62= yypos, yythunkpos62= yythunkpos;  if (!yy_EQUAL()) goto l62;  goto l61;
  l62:;	  yypos= yypos62; yythunkpos= yythunkpos62;
  }  yyDo(yy_3_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l61:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_OPEN()) goto l63;  if (!yy_expression()) goto l63;  if (!yy_CLOSE()) goto l63;  goto l58;
  l63:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_literal()) goto l64;  if (!yymatchChar('i')) goto l64;
  {  int yypos65= yypos, yythunkpos65= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\040\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l65;  goto l64;
  l65:;	  yypos= yypos65; yythunkpos= yythunkpos65;
  }  if (!yy__()) goto l64;  yyDo(yy_4_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l64:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_literal()) goto l66;  yyDo(yy_5_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l66:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_class()) goto l67;  yyDo(yy_6_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l67:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_DOT()) goto l68;  yyDo(yy_7_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l68:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_action()) goto l69;  yyDo(yy_8_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l69:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_MYBEEGIN()) goto l70;  yyDo(yy_9_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l70:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_MYBEGIN()) goto l71;  yyDo(yy_10_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l71:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_MYEEND()) goto l72;  yyDo(yy_11_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l72:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_MYEND()) goto l73;  yyDo(yy_12_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l73:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_BEGIN()) goto l74;  yyDo(yy_13_primary, yybegin, yyend, mybegin, myend);  goto l58;
  l74:;	  yypos= yypos58; yythunkpos= yythunkpos58;  if (!yy_END()) goto l57;  yyDo(yy_14_primary, yybegin, yyend, mybegin, myend);
  }
  l58:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "primary", yyunmatched()));
  return 1;
  l57:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "primary", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_NOT()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "NOT"));  if (!yymatchChar('!')) goto l75;  if (!yy__()) goto l75;
  yyprintf((stderr, "  ok   %s @ %s\n", "NOT", yyunmatched()));
  return 1;
  l75:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NOT", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_suffix()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "suffix"));  if (!yy_primary()) goto l76;
  {  int yypos77= yypos, yythunkpos77= yythunkpos;
  {  int yypos79= yypos, yythunkpos79= yythunkpos;  if (!yy_QUESTION()) goto l80;  yyDo(yy_1_suffix, yybegin, yyend, mybegin, myend);  goto l79;
  l80:;	  yypos= yypos79; yythunkpos= yythunkpos79;  if (!yy_STAR()) goto l81;  yyDo(yy_2_suffix, yybegin, yyend, mybegin, myend);  goto l79;
  l81:;	  yypos= yypos79; yythunkpos= yythunkpos79;  if (!yy_PLUS()) goto l77;  yyDo(yy_3_suffix, yybegin, yyend, mybegin, myend);
  }
  l79:;	  goto l78;
  l77:;	  yypos= yypos77; yythunkpos= yythunkpos77;
  }
  l78:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "suffix", yyunmatched()));
  return 1;
  l76:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "suffix", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_action()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "action"));  if (!yymatchChar('{')) goto l82;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l82;
  l83:;	
  {  int yypos84= yypos, yythunkpos84= yythunkpos;  if (!yy_braces()) goto l84;  goto l83;
  l84:;	  yypos= yypos84; yythunkpos= yythunkpos84;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l82;  if (!yymatchChar('}')) goto l82;  if (!yy__()) goto l82;
  yyprintf((stderr, "  ok   %s @ %s\n", "action", yyunmatched()));
  return 1;
  l82:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "action", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_AND()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "AND"));  if (!yymatchChar('&')) goto l85;  if (!yy__()) goto l85;
  yyprintf((stderr, "  ok   %s @ %s\n", "AND", yyunmatched()));
  return 1;
  l85:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AND", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_prefix()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "prefix"));
  {  int yypos87= yypos, yythunkpos87= yythunkpos;  if (!yy_AND()) goto l88;  if (!yy_action()) goto l88;  yyDo(yy_1_prefix, yybegin, yyend, mybegin, myend);  goto l87;
  l88:;	  yypos= yypos87; yythunkpos= yythunkpos87;  if (!yy_AND()) goto l89;  if (!yy_suffix()) goto l89;  yyDo(yy_2_prefix, yybegin, yyend, mybegin, myend);  goto l87;
  l89:;	  yypos= yypos87; yythunkpos= yythunkpos87;  if (!yy_NOT()) goto l90;  if (!yy_suffix()) goto l90;  yyDo(yy_3_prefix, yybegin, yyend, mybegin, myend);  goto l87;
  l90:;	  yypos= yypos87; yythunkpos= yythunkpos87;  if (!yy_suffix()) goto l86;
  }
  l87:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "prefix", yyunmatched()));
  return 1;
  l86:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "prefix", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_BAR()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "BAR"));  if (!yymatchChar('|')) goto l91;  if (!yy__()) goto l91;
  yyprintf((stderr, "  ok   %s @ %s\n", "BAR", yyunmatched()));
  return 1;
  l91:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BAR", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_sequence()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "sequence"));  if (!yy_prefix()) goto l92;
  l93:;	
  {  int yypos94= yypos, yythunkpos94= yythunkpos;  if (!yy_prefix()) goto l94;  yyDo(yy_1_sequence, yybegin, yyend, mybegin, myend);  goto l93;
  l94:;	  yypos= yypos94; yythunkpos= yythunkpos94;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "sequence", yyunmatched()));
  return 1;
  l92:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "sequence", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_SEMICOLON()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "SEMICOLON"));  if (!yymatchChar(';')) goto l95;  if (!yy__()) goto l95;
  yyprintf((stderr, "  ok   %s @ %s\n", "SEMICOLON", yyunmatched()));
  return 1;
  l95:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SEMICOLON", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_expression()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "expression"));  if (!yy_sequence()) goto l96;
  l97:;	
  {  int yypos98= yypos, yythunkpos98= yythunkpos;  if (!yy_BAR()) goto l98;  if (!yy_sequence()) goto l98;  yyDo(yy_1_expression, yybegin, yyend, mybegin, myend);  goto l97;
  l98:;	  yypos= yypos98; yythunkpos= yythunkpos98;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "expression", yyunmatched()));
  return 1;
  l96:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "expression", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_EQUAL()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "EQUAL"));  if (!yymatchChar('=')) goto l99;  if (!yy__()) goto l99;
  yyprintf((stderr, "  ok   %s @ %s\n", "EQUAL", yyunmatched()));
  return 1;
  l99:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EQUAL", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_identifier()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "identifier"));  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l100;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\040\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l100;
  l101:;	
  {  int yypos102= yypos, yythunkpos102= yythunkpos;  if (!yymatchClass((unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l102;  goto l101;
  l102:;	  yypos= yypos102; yythunkpos= yythunkpos102;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l100;  if (!yy__()) goto l100;
  yyprintf((stderr, "  ok   %s @ %s\n", "identifier", yyunmatched()));
  return 1;
  l100:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "identifier", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_RPERCENT()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "RPERCENT"));  if (!yymatchString("%}")) goto l103;  if (!yy__()) goto l103;
  yyprintf((stderr, "  ok   %s @ %s\n", "RPERCENT", yyunmatched()));
  return 1;
  l103:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RPERCENT", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_end_of_file()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "end_of_file"));
  {  int yypos105= yypos, yythunkpos105= yythunkpos;  if (!yymatchDot()) goto l105;  goto l104;
  l105:;	  yypos= yypos105; yythunkpos= yythunkpos105;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "end_of_file", yyunmatched()));
  return 1;
  l104:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "end_of_file", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_trailer()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "trailer"));  if (!yymatchString("%%")) goto l106;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l106;
  l107:;	
  {  int yypos108= yypos, yythunkpos108= yythunkpos;  if (!yymatchDot()) goto l108;  goto l107;
  l108:;	  yypos= yypos108; yythunkpos= yythunkpos108;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l106;  yyDo(yy_1_trailer, yybegin, yyend, mybegin, myend);
  yyprintf((stderr, "  ok   %s @ %s\n", "trailer", yyunmatched()));
  return 1;
  l106:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "trailer", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_definition()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "definition"));  if (!yy_identifier()) goto l109;  yyDo(yy_1_definition, yybegin, yyend, mybegin, myend);  if (!yy_EQUAL()) goto l109;  if (!yy_expression()) goto l109;  yyDo(yy_2_definition, yybegin, yyend, mybegin, myend);
  {  int yypos110= yypos, yythunkpos110= yythunkpos;  if (!yy_SEMICOLON()) goto l110;  goto l111;
  l110:;	  yypos= yypos110; yythunkpos= yythunkpos110;
  }
  l111:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "definition", yyunmatched()));
  return 1;
  l109:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "definition", yyunmatched()));
  return 0;
}
YY_RULE(int) yy_declaration()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "declaration"));  if (!yymatchString("%{")) goto l112;  yyText(yybegin, yyend);  if (!(YY_BEGIN)) goto l112;
  l113:;	
  {  int yypos114= yypos, yythunkpos114= yythunkpos;
  {  int yypos115= yypos, yythunkpos115= yythunkpos;  if (!yymatchString("%}")) goto l115;  goto l114;
  l115:;	  yypos= yypos115; yythunkpos= yythunkpos115;
  }  if (!yymatchDot()) goto l114;  goto l113;
  l114:;	  yypos= yypos114; yythunkpos= yythunkpos114;
  }  yyText(yybegin, yyend);  if (!(YY_END)) goto l112;  if (!yy_RPERCENT()) goto l112;  yyDo(yy_1_declaration, yybegin, yyend, mybegin, myend);
  yyprintf((stderr, "  ok   %s @ %s\n", "declaration", yyunmatched()));
  return 1;
  l112:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "declaration", yyunmatched()));
  return 0;
}
YY_RULE(int) yy__()
{int mybegin=yybegin, myend=yyend;

  yyprintf((stderr, "%s\n", "_"));
  l117:;	
  {  int yypos118= yypos, yythunkpos118= yythunkpos;
  {  int yypos119= yypos, yythunkpos119= yythunkpos;  if (!yy_space()) goto l120;  goto l119;
  l120:;	  yypos= yypos119; yythunkpos= yythunkpos119;  if (!yy_comment()) goto l118;
  }
  l119:;	  goto l117;
  l118:;	  yypos= yypos118; yythunkpos= yythunkpos118;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yyunmatched()));
  return 1;
}
YY_RULE(int) yy_grammar()
{int mybegin=yybegin, myend=yyend;
  int yypos0= yypos, yythunkpos0= yythunkpos;
  yyprintf((stderr, "%s\n", "grammar"));  if (!yy__()) goto l121;
  {  int yypos124= yypos, yythunkpos124= yythunkpos;  if (!yy_declaration()) goto l125;  goto l124;
  l125:;	  yypos= yypos124; yythunkpos= yythunkpos124;  if (!yy_definition()) goto l121;
  }
  l124:;	
  l122:;	
  {  int yypos123= yypos, yythunkpos123= yythunkpos;
  {  int yypos126= yypos, yythunkpos126= yythunkpos;  if (!yy_declaration()) goto l127;  goto l126;
  l127:;	  yypos= yypos126; yythunkpos= yythunkpos126;  if (!yy_definition()) goto l123;
  }
  l126:;	  goto l122;
  l123:;	  yypos= yypos123; yythunkpos= yythunkpos123;
  }
  {  int yypos128= yypos, yythunkpos128= yythunkpos;  if (!yy_trailer()) goto l128;  goto l129;
  l128:;	  yypos= yypos128; yythunkpos= yythunkpos128;
  }
  l129:;	  if (!yy_end_of_file()) goto l121;
  yyprintf((stderr, "  ok   %s @ %s\n", "grammar", yyunmatched()));
  return 1;
  l121:;	  yypos= yypos0; yythunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "grammar", yyunmatched()));
  return 0;
}
#ifndef YY_PART

typedef int (*yyrule)();

YY_PARSE(int) YYPARSEFROM(yyrule yystart)
{
  int yyok;
  if (!yybuflen)
    {
      yybuflen= 1024;
      yybuf= malloc(yybuflen);
      yytextlen= 1024;
      yytext= malloc(yytextlen);
      yythunkslen= 32;
      yythunks= malloc(sizeof(yythunk) * yythunkslen);
      yyvalslen= 32;
      yyvals= malloc(sizeof(YYSTYPE) * yyvalslen);
      yybegin= yyend= yypos= yylimit= yythunkpos= 0;
    }
  yybegin= yyend= yypos;
  yythunkpos= 0;
  yyval= yyvals;
  yyok= yystart();
  if (yyok) yyDone();
  yyCommit();
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
  (void)yytextmax;
  (void)yyunmatched;
}

YY_PARSE(int) YYPARSE(void)
{
  return YYPARSEFROM(yy_grammar);
}

#endif


void yyerror(char *message)
{
  fprintf(stderr, "%s:%d: %s", fileName, lineNumber, message);
  if (yytext[0]) fprintf(stderr, " near token '%s'", yytext);
  if (yypos < yylimit || !feof(input))
    {
      yybuf[yylimit]= '\0';
      fprintf(stderr, " before text \"");
      while (yypos < yylimit)
	{
	  if ('\n' == yybuf[yypos] || '\r' == yybuf[yypos]) break;
	  fputc(yybuf[yypos++], stderr);
	}
      if (yypos == yylimit)
	{
	  int c;
	  while (EOF != (c= fgetc(input)) && '\n' != c && '\r' != c)
	    fputc(c, stderr);
	}
      fputc('\"', stderr);
    }
  fprintf(stderr, "\n");
  exit(1);
}

void makeHeader(char *text)
{
  Header *header= (Header *)malloc(sizeof(Header));
  header->text= strdup(text);
  header->next= headers;
  headers= header;
}

void makeTrailer(char *text)
{
  trailer= strdup(text);
}

static void version(char *name)
{
  printf("%s version %d.%d.%d\n", name, PEG_MAJOR, PEG_MINOR, PEG_LEVEL);
}

static void usage(char *name)
{
  version(name);
  fprintf(stderr, "usage: %s [<option>...] [<file>...]\n", name);
  fprintf(stderr, "where <option> can be\n");
  fprintf(stderr, "  -h          print this help information\n");
  fprintf(stderr, "  -o <ofile>  write output to <ofile>\n");
  fprintf(stderr, "  -v          be verbose\n");
  fprintf(stderr, "  -V          print version number and exit\n");
  fprintf(stderr, "if no <file> is given, input is read from stdin\n");
  fprintf(stderr, "if no <ofile> is given, output is written to stdout\n");
  exit(1);
}

int main(int argc, char **argv)
{
  Node *n;
  int   c;

  output= stdout;
  input= stdin;
  lineNumber= 1;
  fileName= "<stdin>";

  while (-1 != (c= getopt(argc, argv, "Vho:v")))
    {
      switch (c)
	{
	case 'V':
	  version(basename(argv[0]));
	  exit(0);

	case 'h':
	  usage(basename(argv[0]));
	  break;

	case 'o':
	  if (!(output= fopen(optarg, "w")))
	    {
	      perror(optarg);
	      exit(1);
	    }
	  break;

	case 'v':
	  verboseFlag= 1;
	  break;

	default:
	  fprintf(stderr, "for usage try: %s -h\n", argv[0]);
	  exit(1);
	}
    }
  argc -= optind;
  argv += optind;

  if (argc)
    {
      for (;  argc;  --argc, ++argv)
	{
	  if (!strcmp(*argv, "-"))
	    {
	      input= stdin;
	      fileName= "<stdin>";
	    }
	  else
	    {
	      if (!(input= fopen(*argv, "r")))
		{
		  perror(*argv);
		  exit(1);
		}
	      fileName= *argv;
	    }
	  lineNumber= 1;
	  if (!yyparse())
	    yyerror("syntax error");
	  if (input != stdin)
	    fclose(input);
	}
    }
  else
    if (!yyparse())
      yyerror("syntax error");

  if (verboseFlag)
    for (n= rules;  n;  n= n->any.next)
      Rule_print(n);

  Rule_compile_c_header();

  for (; headers;  headers= headers->next)
    fprintf(output, "%s\n", headers->text);

  if (rules)
    Rule_compile_c(rules);

  if (trailer)
    fprintf(output, "%s\n", trailer);

  return 0;
}

